name: Build MindAR Compiler

on:
  workflow_dispatch:
  push:
    paths:
      - "webar-backend/src/**"
      - "admin.html"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo and submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install system dependencies for node-canvas
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            libcairo2-dev \
            libpango1.0-dev \
            libjpeg-dev \
            libgif-dev \
            librsvg2-dev \
            pkg-config \
            libpixman-1-dev

      - name: Install dependencies
        run: npm install --prefix webar-backend

      - name: Build MindAR compiler
        run: |
          cd mind-ar-js
          npm install
          npm run build

      - name: Deploy to Supabase
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: |
          node webar-backend/src/mindCompiler.js
